title: Technology-enhanced Assessment & Learning Environments (TALE)
description: Technology-enhanced Assessment & Learning Environments
url: "https://apriljzhang.github.io"
baseurl: "/TALE-journal"
markdown: kramdown
permalink: pretty
timezone: UTC

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
